first version done
Artemy22/newProjectToDelete pull request #2
Opened 2023-02-16 23:09 UTC by Artemy22

2023-02-17 06:49 UTC, SanitarskyiDmytro requested changes

2023-02-17 06:49 UTC, SanitarskyiDmytro commented on cypress/support/helper.js
> +    for (let i = 1; i < 5; i++) {
А якщо сторінок в пошуковій видачі буде більше, або менше 4?

2023-02-20 10:04 UTC, Artemy22 commented on cypress/support/helper.js
> +    for (let i = 1; i < 5; i++) {
@SanitarskiyDima refactored.

2023-02-20 19:11 UTC, SanitarskyiDmytro approved these changes

2023-02-21 09:09 UTC, merged